// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlK6fDD1mZ4402EHnNS-3ZAgshzTUzHY0',
    appId: '1:1031933187860:web:4d5f4ac2e0a9efd86e1401',
    messagingSenderId: '1031933187860',
    projectId: 'uber-60ada',
    authDomain: 'uber-60ada.firebaseapp.com',
    storageBucket: 'uber-60ada.appspot.com',
    measurementId: 'G-15HWFP4JS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0AGvOf2A5KrbHwz8NRB6KxVWT9GvyQjQ',
    appId: '1:1031933187860:android:d790ca582f0715da6e1401',
    messagingSenderId: '1031933187860',
    projectId: 'uber-60ada',
    storageBucket: 'uber-60ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFxjgbUR2cC96Ohuc6ata29QuOO36jQeQ',
    appId: '1:1031933187860:ios:da5a3b871e73e95c6e1401',
    messagingSenderId: '1031933187860',
    projectId: 'uber-60ada',
    storageBucket: 'uber-60ada.appspot.com',
    iosClientId: '1031933187860-gqhovh49baq5f9n5bgn4muae0ricf4uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFxjgbUR2cC96Ohuc6ata29QuOO36jQeQ',
    appId: '1:1031933187860:ios:da5a3b871e73e95c6e1401',
    messagingSenderId: '1031933187860',
    projectId: 'uber-60ada',
    storageBucket: 'uber-60ada.appspot.com',
    iosClientId: '1031933187860-gqhovh49baq5f9n5bgn4muae0ricf4uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uber',
  );
}
